# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.9"
            jupyterhub: "2"
          - python: "3.10"
            jupyterhub: "3"
          - python: "3.11"
            jupyterhub: "4"

    steps:
      - uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade --pre -r dev-requirements.txt
          if [[ ! -z "${{ matrix.jupyterhub }}" ]]; then
            pip install jupyterhub==${{ matrix.jupyterhub }}.*
          fi
          pip install -e .

          pip freeze

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Node dependencies
        run: |
          npm install -g configurable-http-proxy

      - name: Run tests
        run: |
          py.test tests
